CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,
    email VARCHAR(128) UNIQUE NOT NULL,
    username varchar(64) UNIQUE NOT NULL,
    password_hash text NOT NULL,
    create_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
)